spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.shtel.security.*.*.model  # 注意：对应实体类的路径

logging:
  config: classpath:log4j2-spring.xml

basic:
  websocURL: http://61.151.249.44
  username: apiadmin
  password: Api.websoc123