spring:
  datasource:
    name: test
    url: jdbc:mysql://39.96.45.191:3306/secure?useTimezone=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: mysql2019!
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # springMVC
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
    static-path-pattern: /**
    favicon:
      enabled: false

server:
  port: 80

#sql语句输出
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
